INSERT INTO `graduation_project_db`.`property_statuses` (`id`,`name`) VALUES (1,'For Sale');
INSERT INTO `graduation_project_db`.`property_statuses` (`id`,`name`) VALUES (2,'For Rent');
INSERT INTO `graduation_project_db`.`user_types` (`id`,`name`) VALUES (1,'seller');
INSERT INTO `graduation_project_db`.`user_types` (`id`,`name`) VALUES (2,'buyer');
INSERT INTO `graduation_project_db`.`user_types` (`id`,`name`) VALUES (3,'employee');
INSERT INTO `graduation_project_db`.`user_types` (`id`,`name`) VALUES (4,'company');

INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (1,'Apartment');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (2,'Villa');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (3,'Townhouse');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (4,'Office');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (5,'Retail');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (6,'Shop');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (7,'Warehouse');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (8,'Building');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (9,'Labour Camp');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (10,'Land');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (11,'Shopping Mall');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (12,'Parking');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (13,'Showroom');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (14,'Full Floor');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (15,'Half Floor');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (16,'Penthouse');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (17,'Hotel Apartment');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (18,'Factory');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (19,'Bulk Units');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (20,'Commercial Building');
INSERT INTO `graduation_project_db`.`property_categories` (`id`,`name`) VALUES (21,'Government Housing');

INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (1,'24 hours Maintenance');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (2,'American Style Kitchen');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (3,'Attach Bath');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (4,'Available Furnished');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (5,'Available Network');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (6,'Balcony');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (7,'Bank/ATM Facility');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (8,'Basement');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (9,'Basement parking');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (10,'Basketball Court');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (11,'BBQ area');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (12,'Beach access');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (13,'Broadband ready');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (14,'Built-in Cupboards');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (15,'Built-in Kitchen Appliances');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (16,'Built-in Kitchen Cabinets');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (17,'Bus services');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (18,'Business Center');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (19,'Cable ready');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (20,'Carpets');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (21,'Central Air Condition');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (22,'Central heating');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (23,'Children daycare');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (24,'Children\'s nursery');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (25,'Chimney');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (26,'City view');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (27,'Cleaning services');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (28,'Clubhouse');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (29,'Communal gardens');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (30,'Community Center');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (31,'Community view');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (32,'Company Maintained');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (33,'Concierge service');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (34,'Concierge Service');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (35,'Core N Shell');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (36,'Covered Parking');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (37,'Cycling tracks');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (38,'Drivers room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (39,'East orientation');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (40,'Elevator');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (41,'Fitness Center');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (42,'Fully fitted kitchen');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (43,'Fully furnished');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (44,'Garden');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (45,'Garden view');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (46,'Gazebo');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (47,'Golf club and clubhouse');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (48,'Golf view');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (49,'Ground floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (50,'GYM');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (51,'Heating');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (52,'High floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (53,'Hospital (nearby)');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (54,'Indoor swimming pool');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (55,'Intercom');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (56,'Jacuzzi');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (57,'Kids Play Area');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (58,'Kitchen Appliances');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (59,'Kitchen white goods');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (60,'Landscaped Garden');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (61,'Laundry Service');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (62,'Laundry/washing room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (63,'Lobby');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (64,'Low floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (65,'Maid Service');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (66,'Maid\'s room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (67,'Maids Room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (68,'Maintenance');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (69,'Marble floors');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (70,'Marina Berth');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (71,'Market (nearby)');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (72,'Metro station');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (73,'Mid floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (74,'Mosque');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (75,'Near airport');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (76,'Near Golf');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (77,'Near Hotel');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (78,'Near mall');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (79,'Near mosque');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (80,'Near veterinary');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (81,'North orientation');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (82,'Office partitions');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (83,'On high floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (84,'On low floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (85,'On mid floor');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (86,'Open View');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (87,'Park Facing');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (88,'Parking');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (89,'Part furnished');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (90,'Pets allowed');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (91,'Polo club and clubhouse');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (92,'Private garage');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (93,'Private garage');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (94,'Private garden');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (95,'Private swimming pool');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (96,'Public park');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (97,'Public parking');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (98,'Public parks');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (99,'Public Transport (nearby)');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (100,'Recreational Facilities');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (101,'Restaurant (nearby)');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (102,'Satellite/Cable TV');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (103,'Sauna');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (104,'School (nearby)');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (105,'Sea/Water view');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (106,'Security');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (107,'Separate Kitchen');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (108,'Separate Laundry');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (109,'Server room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (110,'Shared Gym');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (111,'Shared swimming pool');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (112,'Shopping mall');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (113,'Shops');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (114,'Solid wood floors');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (115,'South orientation');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (116,'Spa');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (117,'Sports academies');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (118,'Squash courts');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (119,'Steam room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (120,'Store Room');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (121,'Study');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (122,'Swimming Pool');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (123,'Tennis courts');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (124,'Terrace');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (125,'Upgraded interior');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (126,'Valet Service');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (127,'View of golf course');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (128,'View of parkland');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (129,'View of sea/water');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (130,'Visitors parking');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (131,'Walk-in Closet');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (132,'Walking Trails');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (133,'West orientation');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (134,'Within a Compound');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (135,'With-in Compound');
INSERT INTO `graduation_project_db`.`features` (`id`,`name`) VALUES (136,'Wood flooring');